libname raw "/userdata20/rroom029/data_source/user_data";/*raw data*/
libname db "/userdata20/rroom029/data_out/data_store"; 
libname db_out "/userdata20/rroom029/data_out/data_out";

DATA DB.TG_FULLDAT; 
MERGE   DB.TARGET_IDBFCDTH (IN=A)   /*CODE: C3334.SAS*/
			 DB.TARGET_LTC_USE /*CODE: LTCUSE.SAS*/
			 DB.TG_CCI /*CODE: CCI.SAS*/
			 DB.TARGET_APLYGRDGRP /*APLYGRDGRP.SAS*/
			 DB.TARGET_TRT /*CODE: TRT.SAS*/ ;
BY INDI_DSCM_NO; IF A=1 ; RUN;        


/*DEMO TABLE용 데이터셋 대상자 : 2009년 이후 진단자, 65세 이상, 타암 기진단자 제외*/
DATA DB.TG_DEMO; SET DB.TG_FULLDAT;
WHERE C_AGE>=65 AND C_YEAR>=2009 AND PRE_C=0;RUN;


/*신청, 인정기간 내 암진단, 인정등급 관련 빈도*/
PROC SQL; CREATE TABLE FQ_APLYGRD AS SELECT EDA_YN, APLY_YN, APLY_BEFC_YN, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.TG_DEMO  WHERE LTC_MAIN_USE IN ('02. 시설','03. 재가')  GROUP BY EDA_YN, APLY_YN, APLY_BEFC_YN ; QUIT;

PROC SQL; CREATE TABLE FQ_APLYGRD_FULL AS SELECT EDA_YN, APLY_YN, APLY_BEFC_YN, LTC_MAIN_USE, MIN_BEFC_GRD_GRP, MIN_GRD_GRP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.TG_DEMO GROUP BY EDA_YN, APLY_YN, APLY_BEFC_YN, LTC_MAIN_USE, MIN_BEFC_GRD_GRP, MIN_GRD_GRP ; QUIT;

/*MAIN USE 서비스가 시설 또는 재가 이지만, 암 진단 이후 2년내 장기요양보험 신청 기록이 없는 사람 5184명 (시설 재가 총 주이용자 22648명의 22.89%)*/
DATA NOAPLYGRP; SET DB.TG_DEMO; WHERE APLY_YN=. AND LTC_MAIN_USE IN ('02. 시설','03. 재가');RUN;
DATA APLYGRP; SET DB.TG_DEMO; WHERE APLY_YN=1 AND LTC_MAIN_USE IN ('02. 시설','03. 재가');RUN;

%MACRO DEMOFREQ(DATASET, COND, CONDNAME);
PROC SQL; CREATE TABLE F1 AS SELECT "01. SEX_TYPE" AS VAR, SEX_TYPE AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY SEX_TYPE; QUIT;
PROC SQL; CREATE TABLE F2 AS SELECT "02. LTC_MAIN_USE" AS VAR, LTC_MAIN_USE AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY LTC_MAIN_USE; QUIT;
PROC SQL; CREATE TABLE F3 AS SELECT "03. C_AGE_GRP2" AS VAR, C_AGE_GRP2 AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY C_AGE_GRP2; QUIT;
PROC SQL; CREATE TABLE F4 AS SELECT "04. INC_QUINTILE" AS VAR, PUT(INC_QUINTILE,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY INC_QUINTILE; QUIT;
PROC SQL; CREATE TABLE F5 AS SELECT "05. RESID_GRP" AS VAR, RESID_GRP AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY RESID_GRP; QUIT;
PROC SQL; CREATE TABLE F6 AS SELECT "06. SIDO_CD" AS VAR, SIDO_CD AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY SIDO_CD; QUIT;
PROC SQL; CREATE TABLE F7 AS SELECT "07. CCI_GRP" AS VAR, CCI_GRP AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY CCI_GRP; QUIT;
PROC SQL; CREATE TABLE F8 AS SELECT "08. C_YEAR_GRP1" AS VAR, C_YEAR_GRP1 AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY C_YEAR_GRP1; QUIT;
PROC SQL; CREATE TABLE F9 AS SELECT "09. SURVIVAL" AS VAR, PUT(SURVIVAL,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY SURVIVAL; QUIT;
PROC SQL; CREATE TABLE F10 AS SELECT "10. 2YR SURVIVAL" AS VAR, PUT(SURVIVAL_2YR,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY SURVIVAL_2YR; QUIT;
PROC SQL; CREATE TABLE F11 AS SELECT "11. MIN_GRD_GRP" AS VAR, PUT(MIN_GRD_GRP,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY MIN_GRD_GRP; QUIT;
PROC SQL; CREATE TABLE F12 AS SELECT "11-1. MIN_BEFC_GRD_GRP" AS VAR, PUT(MIN_BEFC_GRD_GRP,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY MIN_BEFC_GRD_GRP; QUIT;
PROC SQL; CREATE TABLE F13 AS SELECT "12. MIN_GRP" AS VAR, MIN_GRP AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY MIN_GRP; QUIT;
PROC SQL; CREATE TABLE F14 AS SELECT "13. TRT_YN" AS VAR, PUT(TRT_YN,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY TRT_YN; QUIT;
PROC SQL; CREATE TABLE F15 AS SELECT "14. OP_YN" AS VAR, PUT(OP_YN,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY OP_YN; QUIT;
PROC SQL; CREATE TABLE F16 AS SELECT "15. CT_YN" AS VAR, PUT(CT_YN,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY CT_YN; QUIT;
PROC SQL; CREATE TABLE F17 AS SELECT "16. RT_YN" AS VAR, PUT(RT_YN,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY RT_YN; QUIT;

DATA F1; SET F1; FORMAT VAR $20.; FORMAT CLASS $20.;RUN;

DATA FQ&CONDNAME.; LENGTH VAR $20 CLASS $20; SET F1-F17 ;  RUN;
%MEND;

%DEMOFREQ(DATASET=NOAPLYGRP,  CONDNAME=_NOAPLY);
%DEMOFREQ(DATASET=APLYGRP,  CONDNAME=_APLY);

DATA DEMO_APLY_FQ; MERGE FQ_NOAPLY(IN=A) FQ_APLY ; BY VAR CLASS; RUN;



/*Table1,2 Demo*/
/*PRE_C=0, 65세 이상, 2009-2020년 진단*/
%MACRO DEMOFREQ(DATASET, COND, CONDNAME);
PROC SQL; CREATE TABLE F1 AS SELECT "01. SEX_TYPE" AS VAR, SEX_TYPE AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY SEX_TYPE; QUIT;
PROC SQL; CREATE TABLE F2 AS SELECT "02. LTC_MAIN_USE" AS VAR, LTC_MAIN_USE AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY LTC_MAIN_USE; QUIT;
PROC SQL; CREATE TABLE F3 AS SELECT "03. C_AGE_GRP2" AS VAR, C_AGE_GRP2 AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY C_AGE_GRP2; QUIT;
PROC SQL; CREATE TABLE F4 AS SELECT "04. INC_QUINTILE" AS VAR, PUT(INC_QUINTILE,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY INC_QUINTILE; QUIT;
PROC SQL; CREATE TABLE F5 AS SELECT "05. RESID_GRP" AS VAR, RESID_GRP AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY RESID_GRP; QUIT;
PROC SQL; CREATE TABLE F6 AS SELECT "06. SIDO_CD" AS VAR, SIDO_CD AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY SIDO_CD; QUIT;
PROC SQL; CREATE TABLE F7 AS SELECT "07. CCI_GRP" AS VAR, CCI_GRP AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET. &COND. GROUP BY CCI_GRP; QUIT;
PROC SQL; CREATE TABLE F8 AS SELECT "08. C_YEAR_GRP1" AS VAR, C_YEAR_GRP1 AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY C_YEAR_GRP1; QUIT;
PROC SQL; CREATE TABLE F9 AS SELECT "09. SURVIVAL" AS VAR, PUT(SURVIVAL,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY SURVIVAL; QUIT;
PROC SQL; CREATE TABLE F10 AS SELECT "10. 2YR SURVIVAL" AS VAR, PUT(SURVIVAL_2YR,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY SURVIVAL_2YR; QUIT;
PROC SQL; CREATE TABLE F11 AS SELECT "11. MIN_GRD_GRP" AS VAR, PUT(MIN_GRD_GRP,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY MIN_GRD_GRP; QUIT;
DATA DAT_MIN_BEFC_GRD_GRP; SET  &DATASET.; WHERE APLY_YN=.; RUN;
PROC SQL; CREATE TABLE F12 AS SELECT "11.1 MIN_BEFC_GRD_GRP" AS VAR, PUT(MIN_BEFC_GRD_GRP,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM DAT_MIN_BEFC_GRD_GRP  &COND. GROUP BY MIN_BEFC_GRD_GRP; QUIT;
PROC SQL; CREATE TABLE F13 AS SELECT "12. MIN_GRP" AS VAR, MIN_GRP AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.   &COND. GROUP BY MIN_GRP; QUIT;
PROC SQL; CREATE TABLE F14 AS SELECT "13. TRT_YN" AS VAR, PUT(TRT_YN,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY TRT_YN; QUIT;
PROC SQL; CREATE TABLE F15 AS SELECT "14. OP_YN" AS VAR, PUT(OP_YN,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY OP_YN; QUIT;
PROC SQL; CREATE TABLE F16 AS SELECT "15. CT_YN" AS VAR, PUT(CT_YN,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY CT_YN; QUIT;
PROC SQL; CREATE TABLE F17 AS SELECT "16. RT_YN" AS VAR, PUT(RT_YN,1.) AS CLASS, COUNT(DISTINCT INDI_DSCM_NO) AS CNT&CONDNAME. FROM &DATASET.  &COND. GROUP BY RT_YN; QUIT;

DATA F1; SET F1; FORMAT VAR $20.; FORMAT CLASS $20.;RUN;

DATA FQ&CONDNAME.; LENGTH VAR $20 CLASS $20; SET F1-F17 ;  RUN;
%MEND;


%DEMOFREQ(DATASET=DB.TG_DEMO);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='01. 요양병원', CONDNAME=_ADJ);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='02. 시설', CONDNAME=_INS);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='03. 재가', CONDNAME=_HOME);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='04. 이용안함', CONDNAME=_NONE);

%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=1, CONDNAME=_TRT);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=1 AND LTC_MAIN_USE='01. 요양병원', CONDNAME=_TRTADJ);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=1 AND LTC_MAIN_USE='02. 시설', CONDNAME=_TRTINS);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=1 AND LTC_MAIN_USE='03. 재가', CONDNAME=_TRTHOME);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=1 AND LTC_MAIN_USE='04. 이용안함', CONDNAME=_TRTNONE);

%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=0, CONDNAME=_NOTRT);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=0 AND LTC_MAIN_USE='01. 요양병원', CONDNAME=_NOTRTADJ);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=0 AND LTC_MAIN_USE='02. 시설', CONDNAME=_NOTRTINS);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=0 AND LTC_MAIN_USE='03. 재가', CONDNAME=_NOTRTHOME);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=0 AND LTC_MAIN_USE='04. 이용안함', CONDNAME=_NOTRTNONE);

%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE C_AGE_GRP2='01. 65-74', CONDNAME=_6574);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE C_AGE_GRP2='02. 75-84', CONDNAME=_7584);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE C_AGE_GRP2='03. 85+', CONDNAME=_85U);

%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=1 AND C_AGE_GRP2='01. 65-74', CONDNAME=_TRT6574);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=1 AND C_AGE_GRP2='02. 75-84', CONDNAME=_TRT7584);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=1 AND C_AGE_GRP2='03. 85+', CONDNAME=_TRT85U);

%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=0 AND C_AGE_GRP2='01. 65-74', CONDNAME=_NOTRT6574);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=0 AND C_AGE_GRP2='02. 75-84', CONDNAME=_NOTRT7584);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE TRT_YN=0 AND C_AGE_GRP2='03. 85+', CONDNAME=_NOTRT85U);


DATA DB.DEMO_FQ; MERGE FQ(IN=A) FQ_ADJ FQ_INS FQ_HOME FQ_NONE FQ_TRTADJ FQ_TRTINS FQ_TRTHOME FQ_TRTNONE FQ_NOTRTADJ FQ_NOTRTINS FQ_NOTRTHOME FQ_NOTRTNONE
FQ_6574 FQ_7584 FQ_85U FQ_TRT6574 FQ_TRT7584 FQ_TRT85U FQ_NOTRT6574 FQ_NOTRT7584 FQ_NOTRT85U; BY VAR CLASS; RUN;

PROC EXPORT DATA=DB.DEMO_FQ
OUTFILE="/userdata20/rroom029/data_out/data_out/220927/220927_DEMOFQ.xlsx"
DBMS=xlsx REPLACE;
SHEET='SHEET1'
;RUN;


%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE^='04. 이용안함', CONDNAME=_LTCUSE);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='01. 요양병원' AND C_AGE_GRP2='01. 65-74', CONDNAME=_ADJ6574);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='01. 요양병원' AND C_AGE_GRP2='02. 75-84', CONDNAME=_ADJ7584);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='01. 요양병원' AND C_AGE_GRP2='03. 85+', CONDNAME=_ADJ85U);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='02. 시설' AND C_AGE_GRP2='01. 65-74', CONDNAME=_INS6574);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='02. 시설' AND C_AGE_GRP2='02. 75-84', CONDNAME=_INS7584);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='02. 시설' AND C_AGE_GRP2='03. 85+', CONDNAME=_INS85U);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='03. 재가' AND C_AGE_GRP2='01. 65-74', CONDNAME=_HOME6574);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='03. 재가' AND C_AGE_GRP2='02. 75-84', CONDNAME=_HOME7584);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='03. 재가' AND C_AGE_GRP2='03. 85+', CONDNAME=_HOME85U);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='04. 이용안함' AND C_AGE_GRP2='01. 65-74', CONDNAME=_NONE6574);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='04. 이용안함' AND C_AGE_GRP2='02. 75-84', CONDNAME=_NONE7584);
%DEMOFREQ(DATASET=DB.TG_DEMO, COND= WHERE LTC_MAIN_USE='04. 이용안함' AND C_AGE_GRP2='03. 85+', CONDNAME=_NONE85U);

DATA DB.DEMO_FQ_SUPP1; MERGE FQ_LTCUSE(IN=A) FQ_ADJ6574 FQ_ADJ7584 FQ_ADJ85U FQ_INS6574 FQ_INS7584 FQ_INS85U
FQ_HOME6574 FQ_HOME7584 FQ_HOME85U FQ_NONE6574 FQ_NONE7584 FQ_NONE85U ; BY VAR CLASS; RUN;
	
PROC EXPORT DATA=DB.DEMO_FQ_SUPP1
OUTFILE="/userdata20/rroom029/data_out/data_out/220927/220927_DEMO_FQ_SUPP1.xlsx"
DBMS=xlsx REPLACE;
SHEET='SHEET1'
;RUN;


/*Median length of follow up*/

/*Table1. by LTC Service*/
/*Table 1. Baseline characteristics of the study participants by Long-term Care Service*/
/*Median length of follow up*/
%MACRO MST(i,COND,GRP);
PROC LIFETEST DATA=DB.LTC_DUMMYDAT NOTABLE NOPRINT OUTSURV=RES; TIME SURVTIME*DEATH(0);WHERE &COND.; RUN;
PROC SQL; CREATE TABLE TMP0&i. AS SELECT * FROM RES WHERE SURVIVAL>=0.5 ORDER BY SURVIVAL ; QUIT; 
DATA TMP1&i.(KEEP=SURVTIME SURVIVAL); SET TMP0&i.(OBS=1); RUN;
DATA MST&i. ; SET TMP1&i.; FORMAT VAR $20.; VAR=&GRP. ;RUN; 
%MEND;
%MST(i=0, GRP='00. 전체');
%MST(i=1,COND=LTC_MAIN_2YR='01. 요양병원', GRP='01. 요양병원');
%MST(i=2,COND=LTC_MAIN_2YR='02. 시설', GRP='02. 시설');
%MST(i=3,COND=LTC_MAIN_2YR='03. 재가', GRP='03. 재가');
%MST(i=4,COND=LTC_MAIN_2YR='04. NONE', GRP='04. NONE');
DATA DMY_FQ.TB1_MST; SET MST0-MST4; RUN;

/*Table 1a. Baseline characteristics of the study participants by Long-term Care Service in Treatment group*/
/*Median length of follow up*/
%MST(i=0,COND=TRT_ANY_YN=1, GRP='00. 전체');
%MST(i=1,COND=TRT_ANY_YN=1 AND LTC_MAIN_2YR='01. 요양병원', GRP='01. 요양병원');
%MST(i=2,COND=TRT_ANY_YN=1 AND LTC_MAIN_2YR='02. 시설', GRP='02. 시설');
%MST(i=3,COND=TRT_ANY_YN=1 AND LTC_MAIN_2YR='03. 재가', GRP='03. 재가');
%MST(i=4,COND=TRT_ANY_YN=1 AND LTC_MAIN_2YR='04. NONE', GRP='04. NONE');
DATA DMY_FQ.TB1A_MST; SET MST0-MST4; RUN;

/*Table 1b. Baseline characteristics of the study participants by Long-term Care Service in No-treatment group*/
/*Median length of follow up*/
%MST(i=0,COND=TRT_ANY_YN=0, GRP='00. 전체');
%MST(i=1,COND=TRT_ANY_YN=0 AND LTC_MAIN_2YR='01. 요양병원', GRP='01. 요양병원');
%MST(i=2,COND=TRT_ANY_YN=0 AND LTC_MAIN_2YR='02. 시설', GRP='02. 시설');
%MST(i=3,COND=TRT_ANY_YN=0 AND LTC_MAIN_2YR='03. 재가', GRP='03. 재가');
%MST(i=4,COND=TRT_ANY_YN=0 AND LTC_MAIN_2YR='04. NONE', GRP='04. NONE');
DATA DMY_FQ.TB1B_MST; SET MST0-MST4; RUN;


/*Table2. by Age*/
/*Table 2. Baseline characteristics of the study participants by Age*/
/*Median length of follow up*/
%MST(i=0, GRP='00. 전체');
%MST(i=1,COND=E_AGE_GRP='01. 65-74',GRP='01. 65-74');
%MST(i=2,COND=E_AGE_GRP='02. 75-84',GRP='02. 75-84');
%MST(i=3,COND=E_AGE_GRP='03. 85+', GRP='03. 85+');
DATA DMY_FQ.TB2_MST; SET MST0-MST3; RUN;

/*Table 2a. Baseline characteristics of the study participants by Age in Treatment group*/
/*Median length of follow up*/
%MST(i=0,COND=TRT_ANY_YN=1, GRP='00. 전체');
%MST(i=1,COND=TRT_ANY_YN=1 AND E_AGE_GRP='01. 65-74', GRP='01. 65-74');
%MST(i=2,COND=TRT_ANY_YN=1 AND E_AGE_GRP='02. 75-84', GRP='02. 75-84');
%MST(i=3,COND=TRT_ANY_YN=1 AND E_AGE_GRP='03. 85+', GRP='03. 85+');
DATA DMY_FQ.TB2A_MST; SET MST0-MST3; RUN;

/*Table 2b. Baseline characteristics of the study participants by Age in No-treatment group*/
/*Median length of follow up*/
%MST(i=0,COND=TRT_ANY_YN=0, GRP='00. 전체');
%MST(i=1,COND=TRT_ANY_YN=0 AND E_AGE_GRP='01. 65-74', GRP='01. 65-74');
%MST(i=2,COND=TRT_ANY_YN=0 AND E_AGE_GRP='02. 75-84', GRP='02. 75-84');
%MST(i=3,COND=TRT_ANY_YN=0 AND E_AGE_GRP='03. 85+', GRP='03. 85+');
DATA DMY_FQ.TB2B_MST; SET MST0-MST3; RUN;





DATA TRT_DIST; SET DB.TG_DEMO; 
FORMAT C_AGE_GRP3 $20.;
IF 40<=C_AGE<=64 THEN C_AGE_GRP3="01. 40-64";
ELSE IF 65<=C_AGE<=74 THEN C_AGE_GRP3="02. 65-74";
ELSE IF 75<=C_AGE THEN C_AGE_GRP3="03. 75+";
FORMAT TRT_GRP $30.;
IF OP_YN=1 AND CT_YN=0 AND RT_YN=0 THEN TRT_GRP="01. SURGERY ONLY";
IF OP_YN=1 AND CT_YN=1 AND RT_YN=0 THEN TRT_GRP="02. SURGERY + CTx";
IF OP_YN=1 AND CT_YN=1 AND RT_YN=1 THEN TRT_GRP="03. SURGERY + CTx + RT";
IF OP_YN=1 AND CT_YN=0 AND RT_YN=1 THEN TRT_GRP="04. SURGERY + RT";
IF OP_YN=0 AND CT_YN=1 AND RT_YN=0 THEN TRT_GRP="05. CTx";
IF OP_YN=0 AND CT_YN=1 AND RT_YN=1 THEN TRT_GRP="06. CTx + RT";
IF OP_YN=0 AND CT_YN=0 AND RT_YN=1 THEN TRT_GRP="07. RT";
WHERE TRT_YN=1;
RUN;

PROC SQL; CREATE TABLE TRT_GRP_DIST AS SELECT C_AGE_GRP3, TRT_GRP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM TRT_DIST WHERE C_AGE>=40 GROUP BY C_AGE_GRP3,TRT_GRP; QUIT;

PROC SQL; CREATE TABLE OP_DIST AS SELECT C_AGE_GRP3, OP_CTG, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM TRT_DIST WHERE OP_YN=1 AND C_AGE>=40 GROUP BY C_AGE_GRP3, OP_CTG ; QUIT;
PROC SQL; CREATE TABLE OP_ONLY_DIST AS SELECT C_AGE_GRP3, OP_CTG, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM TRT_DIST WHERE TRT_GRP="01. SURGERY ONLY" AND C_AGE>=40 GROUP BY C_AGE_GRP3, OP_CTG; QUIT;




PROC EXPORT DATA=TRT_GRP_DIST
OUTFILE="/userdata20/rroom029/data_out/data_out/220824/220824_TRT_GRP_DIST.xlsx"
DBMS=xlsx REPLACE;
SHEET='SHEET1';
RUN;
PROC EXPORT DATA=OP_DIST
OUTFILE="/userdata20/rroom029/data_out/data_out/220824/220824_OP_DIST.xlsx"
DBMS=xlsx REPLACE;
SHEET='SHEET1';
RUN;
PROC EXPORT DATA=OP_ONLY_DIST
OUTFILE="/userdata20/rroom029/data_out/data_out/220824/220824_OP_ONLY_DIST.xlsx"
DBMS=xlsx REPLACE;
SHEET='SHEET1';
RUN;



/*항암제별 빈도*/
PROC SQL; CREATE TABLE CTx_CNT AS SELECT CTx, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.TARGET_T30_LTC2YR GROUP BY CTx; QUIT;

PROC SQL; CREATE TABLE CTx_CNT2 AS SELECT C_YEAR, CT_CYTYN, CT_TARYN, CT_IMUYN, CT_OTHYN, CTx, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.TARGET_T30_LTC2YR GROUP BY C_YEAR, CT_CYTYN, CT_TARYN, CT_IMUYN, CT_OTHYN, CTx; QUIT;

/*65세 이상*/
PROC SQL; CREATE TABLE CTx_CNT65U AS SELECT CTx, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.TARGET_T30_LTC2YR WHERE C_AGE>=65 GROUP BY CTx; QUIT;

PROC SQL; CREATE TABLE CTx_CNT265U AS SELECT C_AGE_GRP2, C_YEAR, CT_CYTYN, CT_TARYN, CT_IMUYN, CT_OTHYN, CTx, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.TARGET_T30_LTC2YR WHERE C_AGE>=65  GROUP BY C_AGE_GRP2, C_YEAR, CT_CYTYN, CT_TARYN, CT_IMUYN, CT_OTHYN, CTx; QUIT;


/*수술별 빈도*/
PROC SQL; CREATE TABLE OP_CNT AS SELECT OP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM FIRST_OP_T30 GROUP BY OP; QUIT;
/*65세 이상*/
