libname raw "/userdata20/rroom029/data_source/user_data";/*raw data*/
libname db "/userdata20/rroom029/data_out/data_store"; 
libname db_out "/userdata20/rroom029/data_out/data_out";

%LET YEAR=2008;
%LET YM=200801;

%MACRO YEARLY; %DO YEAR=2008 %TO 2020;

	%MACRO MONTHLY(STRT, STP); 

	%DO YM=&STRT. %TO &STP.;

	/*대상자 20테이블DB*/
	PROC SQL; CREATE TABLE TARGET_T20_&YM. AS
	SELECT DISTINCT A.*, B.CMN_KEY, B.MDCARE_SYM, B.MDCARE_STRT_DT, B.VSHSP_DD_CNT, B.MDCARE_DD_CNT, B.TOT_PRSC_DD_CNT
	FROM DB.TARGET_ID AS A
	INNER JOIN RAW.T20_&YM. AS B
	ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
	; QUIT;

	/*대상자 30테이블DB*/
	PROC SQL; CREATE TABLE TARGET_T30_&YM. AS
	SELECT DISTINCT A.*, B.MCARE_DIV_CD_ADJ
	FROM TARGET_T20_&YM. AS A
	INNER JOIN RAW.T30_&YM. AS B
	ON A.CMN_KEY=B.CMN_KEY
	WHERE SUBSTR(B.MCARE_DIV_CD_ADJ,1,5) IN ("A1100","A1900","A2100","A2900","A3000","A3100","A3900","A6100","A6900","A7100","A7900") 
	; QUIT;

	%END; 
	%MEND MONTHLY;  

	%MONTHLY(STRT=&YEAR.01, STP=&YEAR.12);

DATA DB.TARGET_ADJ_&YEAR.; SET TARGET_T30_&YEAR.01-TARGET_T30_&YEAR.12; RUN;

%END; 
%MEND YEARLY;%YEARLY;


DATA DB.TARGET_ADJ; SET DB.TARGET_ADJ_2008-DB.TARGET_ADJ_2020; RUN;


/****** 시설 및 재가 이용 데이터 ******/
PROC SQL; CREATE TABLE DB.TARGET_LTCP AS
SELECT DISTINCT A.*, B.INDI_SEQ, B.LTCP_OFFR_YYYYMM, B.LTCP_FR_DT, B.LTCP_TYPE_CD, B.EADJ_TOTAL_PAY_DCNT
FROM DB.TARGET_ID AS A
LEFT JOIN RAW.RVSN_HFVT_TBNYPAY AS B
ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
WHERE B.LTCP_TYPE_CD IN ('1','2')
; QUIT;


PROC SORT DATA=DB.TARGET_ADJ; BY INDI_DSCM_NO; RUN;
DATA FIRST_ADJ_USE; SET DB.TARGET_ADJ ; BY INDI_DSCM_NO; IF FIRST.INDI_DSCM_NO; 
WHERE C_DATE <= INPUT(MDCARE_STRT_DT,YYMMDD10.) ; RUN;

DATA FIRST_INS_USE; SET DB.TARGET_LTCP ; BY INDI_DSCM_NO; IF FIRST.INDI_DSCM_NO; 
WHERE C_DATE <= INPUT(LTCP_FR_DT,YYMMDD10.) AND LTCP_TYPE_CD='1'; RUN;

DATA FIRST_HOME_USE; SET DB.TARGET_LTCP ; BY INDI_DSCM_NO; IF FIRST.INDI_DSCM_NO; 
WHERE C_DATE <= INPUT(LTCP_FR_DT,YYMMDD10.) AND LTCP_TYPE_CD='2'; RUN;


DATA ADJUSE_STRTYR; SET FIRST_ADJ_USE;
IF INPUT(MDCARE_STRT_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,2,'S') THEN ADJ_STYR_GRP='0-2년';
IF INTNX('YEAR',C_DATE,2,'S') < INPUT(MDCARE_STRT_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,3,'S') THEN ADJ_STYR_GRP='2-3년';
IF INTNX('YEAR',C_DATE,3,'S') < INPUT(MDCARE_STRT_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,4,'S') THEN ADJ_STYR_GRP='3-4년';
IF INTNX('YEAR',C_DATE,4,'S') < INPUT(MDCARE_STRT_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,5,'S') THEN ADJ_STYR_GRP='4-5년';
IF INTNX('YEAR',C_DATE,5,'S') < INPUT(MDCARE_STRT_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,6,'S') THEN ADJ_STYR_GRP='5-6년';
IF INTNX('YEAR',C_DATE,6,'S') < INPUT(MDCARE_STRT_DT,YYMMDD10.)  THEN ADJ_STYR_GRP='6+년'; RUN;

DATA INSUSE_STRTYR; SET FIRST_INS_USE;
IF INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,2,'S') THEN INS_STYR_GRP='0-2년';
IF INTNX('YEAR',C_DATE,2,'S') < INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,3,'S') THEN INS_STYR_GRP='2-3년';
IF INTNX('YEAR',C_DATE,3,'S') < INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,4,'S') THEN INS_STYR_GRP='3-4년';
IF INTNX('YEAR',C_DATE,4,'S') < INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,5,'S') THEN INS_STYR_GRP='4-5년';
IF INTNX('YEAR',C_DATE,5,'S') < INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,6,'S') THEN INS_STYR_GRP='5-6년';
IF INTNX('YEAR',C_DATE,6,'S') < INPUT(LTCP_FR_DT,YYMMDD10.)  THEN INS_STYR_GRP='6+년'; RUN;

DATA HOMEUSE_STRTYR; SET FIRST_HOME_USE;
IF INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,2,'S') THEN HOME_STYR_GRP='0-2년';
IF INTNX('YEAR',C_DATE,2,'S') < INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,3,'S') THEN HOME_STYR_GRP='2-3년';
IF INTNX('YEAR',C_DATE,3,'S') < INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,4,'S') THEN HOME_STYR_GRP='3-4년';
IF INTNX('YEAR',C_DATE,4,'S') < INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,5,'S') THEN HOME_STYR_GRP='4-5년';
IF INTNX('YEAR',C_DATE,5,'S') < INPUT(LTCP_FR_DT,YYMMDD10.) <= INTNX('YEAR',C_DATE,6,'S') THEN HOME_STYR_GRP='5-6년';
IF INTNX('YEAR',C_DATE,6,'S') < INPUT(LTCP_FR_DT,YYMMDD10.)  THEN HOME_STYR_GRP='6+년'; RUN;

PROC SQL; CREATE TABLE LTCYR_DUMMY0 AS SELECT A.*,B.ADJ_STYR_GRP FROM DB.LTC_DUMMYDAT AS A
LEFT JOIN ADJUSE_STRTYR AS B ON A.INDI_DSCM_NO=B.INDI_DSCM_NO;QUIT;
PROC SQL; CREATE TABLE LTCYR_DUMMY1 AS SELECT A.*,B.INS_STYR_GRP FROM LTCYR_DUMMY0 AS A
LEFT JOIN INSUSE_STRTYR AS B ON A.INDI_DSCM_NO=B.INDI_DSCM_NO;QUIT;
PROC SQL; CREATE TABLE LTCYR_DUMMY2 AS SELECT A.*,B.HOME_STYR_GRP FROM LTCYR_DUMMY1 AS A
LEFT JOIN HOMEUSE_STRTYR AS B ON A.INDI_DSCM_NO=B.INDI_DSCM_NO;QUIT;

DATA LTCYR_DUMMY; SET LTCYR_DUMMY2; 
FORMAT ADJ_STYR_GRP $20.; FORMAT INS_STYR_GRP $20.; FORMAT HOME_STYR_GRP $20.;
IF ADJ_STYR_GRP='' THEN ADJ_STYR_GRP='NOUSE'; 
IF INS_STYR_GRP='' THEN INS_STYR_GRP='NOUSE'; 
IF HOME_STYR_GRP='' THEN HOME_STYR_GRP='NOUSE'; RUN;

PROC FREQ DATA=LTCYR_DUMMY NOPRINT; TABLES ADJ_STYR_GRP*SEX_TYPE /OUT=FREQ22222 ; WHERE ADJ_STYR_GRP='2-3년'; RUN;

%LET VARLIST= SEX_TYPE/E_AGE_GRP/INC_QUINTILE/RESID_GRP/CCI_GRP/SURVIVAL/TRT_ANY_YN/OP_2YR_YN/CT_2YR_YN/RT_2YR_YN;
%LET N_VAR=10;
%MACRO FREQ(COND);
%DO i=1 %TO &N_VAR.; %LET VAR = %SCAN(&VARLIST., &i, "/");
	PROC FREQ DATA=LTCYR_DUMMY NOPRINT; TABLES ADJ_STYR_GRP*&VAR. /OUT=FREQ&i. (DROP=PERCENT); WHERE &COND.; RUN;
%END;
%MEND FREQ; 
%FREQ(); 
DATA ADJ_02; SET FREQ1-FREQ&N_VAR.; WHERE ADJ_STYR_GRP='0-2년'; RUN;
DATA ADJ_23; SET FREQ1-FREQ&N_VAR.; WHERE ADJ_STYR_GRP='2-3년'; RUN;
DATA ADJ_34; SET FREQ1-FREQ&N_VAR.; WHERE ADJ_STYR_GRP='3-4년'; RUN;
DATA ADJ_45; SET FREQ1-FREQ&N_VAR.; WHERE ADJ_STYR_GRP='4-5년'; RUN;
DATA ADJ_56; SET FREQ1-FREQ&N_VAR.; WHERE ADJ_STYR_GRP='5-6년'; RUN;
DATA ADJ_6; SET FREQ1-FREQ&N_VAR.; WHERE ADJ_STYR_GRP='6+년'; RUN;
%MACRO FREQ(COND);
%DO i=1 %TO &N_VAR.; %LET VAR = %SCAN(&VARLIST., &i, "/");
	PROC FREQ DATA=LTCYR_DUMMY NOPRINT; TABLES INS_STYR_GRP*&VAR. /OUT=FREQ&i. (DROP=PERCENT); WHERE &COND.; RUN;
%END;
%MEND FREQ; 
%FREQ(); 
DATA INS_02; SET FREQ1-FREQ&N_VAR.; WHERE INS_STYR_GRP='0-2년'; RUN;
DATA INS_23; SET FREQ1-FREQ&N_VAR.; WHERE INS_STYR_GRP='2-3년'; RUN;
DATA INS_34; SET FREQ1-FREQ&N_VAR.; WHERE INS_STYR_GRP='3-4년'; RUN;
DATA INS_45; SET FREQ1-FREQ&N_VAR.; WHERE INS_STYR_GRP='4-5년'; RUN;
DATA INS_56; SET FREQ1-FREQ&N_VAR.; WHERE INS_STYR_GRP='5-6년'; RUN;
DATA INS_6; SET FREQ1-FREQ&N_VAR.; WHERE INS_STYR_GRP='6+년'; RUN;
%MACRO FREQ(COND);
%DO i=1 %TO &N_VAR.; %LET VAR = %SCAN(&VARLIST., &i, "/");
	PROC FREQ DATA=LTCYR_DUMMY NOPRINT; TABLES HOME_STYR_GRP*&VAR. /OUT=FREQ&i.(DROP=PERCENT); WHERE &COND.; RUN;
%END;
%MEND FREQ; 
%FREQ(); 
DATA HOME_02; SET FREQ1-FREQ&N_VAR.; WHERE HOME_STYR_GRP='0-2년'; RUN;
DATA HOME_23; SET FREQ1-FREQ&N_VAR.; WHERE HOME_STYR_GRP='2-3년'; RUN;
DATA HOME_34; SET FREQ1-FREQ&N_VAR.; WHERE HOME_STYR_GRP='3-4년'; RUN;
DATA HOME_45; SET FREQ1-FREQ&N_VAR.; WHERE HOME_STYR_GRP='4-5년'; RUN;
DATA HOME_56; SET FREQ1-FREQ&N_VAR.; WHERE HOME_STYR_GRP='5-6년'; RUN;
DATA HOME_6; SET FREQ1-FREQ&N_VAR.; WHERE HOME_STYR_GRP='6+년'; RUN;


/*ADJ 명세서별 요양 최종일자 구하기 MDCARE_END_DT = MDCARE_STRT_DT + MDCARE_DD_CNT*/
DATA TARGET_ADJ; SET DB.TARGET_ADJ;
MDCARE_STRT_DT2 = INPUT(MDCARE_STRT_DT,YYMMDD10.);
MDCARE_END_DT = MDCARE_STRT_DT2 + MDCARE_DD_CNT;RUN;
/*TBNYPAY별 심사조정총급여최종일자 구하기 LTCP_END_DT = LTCP_FR_DT + EADJ_TOTAL_PAY_DCNT*/
DATA TARGET_LTCP; SET DB.TARGET_LTCP;
LTCP_FR_DT2 = INPUT(LTCP_FR_DT,YYMMDD10.);
LTCP_END_DT = LTCP_FR_DT2 + EADJ_TOTAL_PAY_DCNT;RUN;




/*ADJ 암 진단 이후 2년 내 이용 건*/
DATA TARGET_ADJ_2YR1; SET TARGET_ADJ;
WHERE C_DATE<=MDCARE_STRT_DT2 AND MDCARE_END_DT<=INTNX('YEAR',C_DATE,2,'S');RUN;
DATA TARGET_ADJ_2YR2; SET TARGET_ADJ;
MDCARE_END_DT=INTNX('YEAR',C_DATE,2,'S');
WHERE MDCARE_STRT_DT2<=INTNX('YEAR',C_DATE,2,'S') AND MDCARE_END_DT>INTNX('YEAR',C_DATE,2,'S');RUN;
DATA TARGET_ADJ_2YR; SET TARGET_ADJ_2YR1 TARGET_ADJ_2YR2; RUN;
/*INS 암진단 이후 2년 내 이용 건*/
DATA TARGET_INS_2YR1; SET TARGET_LTCP;
WHERE C_DATE<=LTCP_FR_DT2 AND LTCP_END_DT<=INTNX('YEAR',C_DATE,2,'S') AND LTCP_TYPE_CD = '1';RUN;
DATA TARGET_INS_2YR2; SET TARGET_LTCP;
LTCP_END_DT=INTNX('YEAR',C_DATE,2,'S');
WHERE LTCP_FR_DT2<=INTNX('YEAR',C_DATE,2,'S') AND LTCP_END_DT>INTNX('YEAR',C_DATE,2,'S') AND LTCP_TYPE_CD = '1';RUN;
DATA TARGET_INS_2YR; SET TARGET_INS_2YR1 TARGET_INS_2YR2; RUN;
/*HOME 암진단 이후 2년 내 이용 건*/
DATA TARGET_HOME_2YR1; SET TARGET_LTCP;
WHERE C_DATE<=LTCP_FR_DT2 AND LTCP_END_DT<=INTNX('YEAR',C_DATE,2,'S') AND LTCP_TYPE_CD = '2';RUN;
DATA TARGET_HOME_2YR2; SET TARGET_LTCP;
LTCP_END_DT=INTNX('YEAR',C_DATE,2,'S');
WHERE LTCP_FR_DT2<=INTNX('YEAR',C_DATE,2,'S') AND LTCP_END_DT>INTNX('YEAR',C_DATE,2,'S') AND LTCP_TYPE_CD = '2';RUN;
DATA TARGET_HOME_2YR; SET TARGET_HOME_2YR1 TARGET_HOME_2YR2; RUN;

/*개인별로 MIN MAX구하기*/
PROC SQL; CREATE TABLE ADJ_2YR_MINMAX AS SELECT INDI_DSCM_NO, MIN(MDCARE_STRT_DT2) AS MIN_DT, MAX(MDCARE_END_DT) AS MAX_DT
FROM TARGET_ADJ_2YR GROUP BY INDI_DSCM_NO ORDER BY INDI_DSCM_NO; QUIT;
PROC SQL; CREATE TABLE INS_2YR_MINMAX AS SELECT INDI_DSCM_NO, MIN(LTCP_FR_DT2) AS MIN_DT, MAX(LTCP_END_DT) AS MAX_DT
FROM TARGET_INS_2YR GROUP BY INDI_DSCM_NO ORDER BY INDI_DSCM_NO; QUIT;
PROC SQL; CREATE TABLE HOME_2YR_MINMAX AS SELECT INDI_DSCM_NO, MIN(LTCP_FR_DT2) AS MIN_DT, MAX(LTCP_END_DT) AS MAX_DT
FROM TARGET_HOME_2YR GROUP BY INDI_DSCM_NO ORDER BY INDI_DSCM_NO; QUIT;

/*개인별 이용기간(MAX-MIN) 구하기*/
DATA ADJ_2YR_TOTDD(KEEP= INDI_DSCM_NO ADJ_DD); SET ADJ_2YR_MINMAX; ADJ_DD = MAX_DT-MIN_DT; RUN;
DATA INS_2YR_TOTDD(KEEP= INDI_DSCM_NO INS_DD); SET INS_2YR_MINMAX; INS_DD = MAX_DT-MIN_DT; RUN;
DATA HOME_2YR_TOTDD(KEEP= INDI_DSCM_NO HOME_DD); SET HOME_2YR_MINMAX; HOME_DD = MAX_DT-MIN_DT; RUN;

/*각 서비스 이용일 수 MERGE*/
DATA LTC_USE_2YR; MERGE ADJ_2YR_TOTDD INS_2YR_TOTDD HOME_2YR_TOTDD; BY INDI_DSCM_NO; RUN;

/*암 진단이후 2년 내 최다 이용일 수, 최다일 이용 기관*/
DATA MAX_DD_2YR; SET LTC_USE_2YR;
N_2YR = N(OF ADJ_DD,INS_DD, HOME_DD); /*이용한 */
MAX_DD_2YR = MAX(ADJ_DD,INS_DD, HOME_DD);
IF MAX_DD_2YR = ADJ_DD THEN MAIN_USE_2YR = '01. 요양병원';
ELSE IF MAX_DD_2YR = INS_DD THEN MAIN_USE_2YR = '02. 시설';
ELSE IF MAX_DD_2YR = HOME_DD THEN MAIN_USE_2YR = '03. 재가'
; RUN;

PROC FREQ DATA=MAX_DD_2YR; TABLES N_2YR;RUN;
PROC UNIVARIATE DATA=MAX_DD_2YR; VAR ADJ_DD ; HISTOGRAM; WHERE ADJ_DD^=.;RUN;
PROC UNIVARIATE DATA=MAX_DD_2YR; VAR INS_DD ; HISTOGRAM; WHERE INS_DD^=.;RUN;
PROC UNIVARIATE DATA=MAX_DD_2YR; VAR HOME_DD ; HISTOGRAM; WHERE HOME_DD^=.;RUN;

PROC FREQ DATA=MAX_DD_2YR; TABLES MAIN_USE_2YR;RUN;

/*여러개 서비스를 이용하는 사람 수*/
DATA MULTI_USE_2YR; SET MAX_DD_2YR;
FORMAT USE_GRP $20.;
IF ADJ_DD^=. THEN ADJ=1 ;ELSE ADJ=0;
IF INS_DD^=. THEN INS=1 ;ELSE INS=0;
IF HOME_DD^=. THEN HOME=1; ELSE HOME=0;
IF ADJ=0 AND INS=0 AND HOME=0 THEN USE_GRP='00. NONE';
IF ADJ=1 AND INS=0 AND HOME=0 THEN USE_GRP='01. ONLY ADJ';
IF ADJ=0 AND INS=1 AND HOME=0 THEN USE_GRP='02. ONLY INS';
IF ADJ=0 AND INS=0 AND HOME=1 THEN USE_GRP='03. ONLY HOME';
IF ADJ=1 AND INS=1 AND HOME=0 THEN USE_GRP='04. ADJ+INS';
IF ADJ=1 AND INS=0 AND HOME=1 THEN USE_GRP='05. ADJ+HOME';
IF ADJ=0 AND INS=1 AND HOME=1 THEN USE_GRP='06. INS+HOME';
IF ADJ=1 AND INS=1 AND HOME=1 THEN USE_GRP='07. ADJ+INS_HOME';
RUN;

PROC FREQ DATA=MULTI_USE_2YR;TABLES USE_GRP;RUN;


/*2개 서비스를 이용하는 경우 서비스 간 이용일 수 차이는?*/
DATA USE2_2YR; SET MULTI_USE_2YR; 
IF USE_GRP='04. ADJ+INS' THEN DIFF=ABS(ADJ_DD-INS_DD);
IF USE_GRP='05. ADJ+HOME' THEN DIFF=ABS(ADJ_DD-HOME_DD);
IF USE_GRP='06. INS+HOME' THEN DIFF=ABS(HOME_DD-INS_DD);
WHERE USE_GRP IN ('04. ADJ+INS','05. ADJ+HOME','06. INS+HOME');
RUN;

PROC UNIVARIATE DATA=USE2_2YR; VAR DIFF; HISTOGRAM; RUN;
PROC UNIVARIATE DATA=USE2_2YR; VAR DIFF; HISTOGRAM; WHERE DIFF<90;RUN;

PROC FREQ DATA=USE2_2YR;TABLES USE_GRP; WHERE DIFF<30; RUN;
PROC FREQ DATA=USE2_2YR;TABLES USE_GRP; WHERE DIFF<15; RUN;

PROC SGPLOT DATA=USE2_2YR; VBAR DIFF; RUN; /*JVM 오류*/


/*타암기진단여부, 성별, 연령, 진단일, 진단연도, 사망일에 메인이용서비스 붙이기*/
PROC SQL; CREATE TABLE LTC_FULLDAT0 AS
SELECT A.INDI_DSCM_NO, A.PRE_C, A.SEX_TYPE, A.C_AGE, A.C_YEAR, A.C_DATE, A.DTH_DATE, B.MAIN_USE_2YR
FROM DB.TARGET_DTH AS A
LEFT JOIN MAX_DD_2YR AS B
ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
;QUIT;

/*서비스 미이용 그룹 표시, 연령 그룹 나누기, 연도 그룹 나누기, SURVTIME 계산, */
DATA LTC_FULLDAT1/*(DROP=C_AGE C_DATE DTH_DATE)*/; SET LTC_FULLDAT0;
IF MAIN_USE_2YR ='' THEN MAIN_USE_2YR='04. NONE';

IF C_AGE>= 85 THEN AGE_GRP=18;
ELSE AGE_GRP= FLOOR(C_AGE/5)+1;

IF 65<= C_AGE<75 THEN E_AGE_GRP='01. 65-74'; /*ELDERLY AGE GRP*/
ELSE IF 75 <= C_AGE <85 THEN E_AGE_GRP='02. 75-84';
ELSE IF 78 <= C_AGE THEN E_AGE_GRP='03. 85+';

/*IF C_YEAR IN (2008,2009,2010) THEN C_YEAR_GRP="01. 2008-2010";
IF C_YEAR IN (2011,2012,2013) THEN C_YEAR_GRP="02. 2011-2013";
IF C_YEAR IN (2014,2015,2016) THEN C_YEAR_GRP="03. 2014-2016";
IF C_YEAR IN (2017,2018,2019) THEN C_YEAR_GRP="04. 2017-2019";*/

IF DTH_DATE^=. THEN DO;SURVTIME=DTH_DATE-C_DATE; DEATH=1;END;
ELSE IF DTH_DATE=. THEN DO;SURVTIME=INPUT(PUT('20211021',8.), YYMMDD10.)-C_DATE; DEATH=0;END;
IF SURVTIME<=0 THEN SURVTIME=0.5;

/*마지막 DTH_ASSMD_DT = 20211021*/
/*PROC SQL; CREATE TABLE DTH_DT AS SELECT DTH_ASSMD_DT FROM RAW.TG_DTH ORDER BY DTH_ASSMD_DT; QUIT; */
/*SURVTIME=0 : 273(177)명, <0 : 3(2)명*/
/*DATA TEST; SET LTC_FULLDAT0; 
IF DTH_DATE^=. THEN DO;SURVTIME=DTH_DATE-C_DATE; DEATH=1;END;
ELSE IF DTH_DATE=. THEN DO;SURVTIME=INPUT(PUT('20211021',8.), YYMMDD10.)-C_DATE; DEATH=0;END ; RUN;
DATA TEST2; SET TEST; WHERE SURVTIME=0 AND PRE_C=0;RUN;
DATA TEST3; SET TEST; WHERE SURVTIME<0 AND PRE_C=0;RUN;*/

/*2(+3, 5)년내 생존 곡선 그리기*/
IF DEATH=1 AND SURVTIME<=365*2 THEN DO;DEATH_2YR=1;SURVTIME_2YR=SURVTIME;END;
ELSE IF DEATH=1 AND SURVTIME>365*2 THEN DO;DEATH_2YR=0; SURVTIME_2YR=365*2;END;
ELSE IF DEATH=0 AND SURVTIME<=365*2 THEN DO;DEATH_2YR=0; SURVTIME_2YR=SURVTIME;END;
ELSE IF DEATH=0 AND SURVTIME>365*2 THEN DO;DEATH_2YR=0; SURVTIME_2YR=365*2;END;

IF DEATH=1 AND SURVTIME<=365*3 THEN DO;DEATH_3YR=1;SURVTIME_3YR=SURVTIME;END;
ELSE IF DEATH=1 AND SURVTIME>365*3 THEN DO;DEATH_3YR=0; SURVTIME_3YR=365*3;END;
ELSE IF DEATH=0 AND SURVTIME<=365*3 THEN DO;DEATH_3YR=0; SURVTIME_3YR=SURVTIME;END;
ELSE IF DEATH=0 AND SURVTIME>365*3 THEN DO;DEATH_3YR=0; SURVTIME_3YR=365*3;END;

IF DEATH=1 AND SURVTIME<=365*5 THEN DO;DEATH_5YR=1;SURVTIME_5YR=SURVTIME;END;
ELSE IF DEATH=1 AND SURVTIME>365*5 THEN DO;DEATH_5YR=0; SURVTIME_5YR=365*5;END;
ELSE IF DEATH=0 AND SURVTIME<=365*5 THEN DO;DEATH_5YR=0; SURVTIME_5YR=SURVTIME;END;
ELSE IF DEATH=0 AND SURVTIME>365*5 THEN DO;DEATH_5YR=0; SURVTIME_5YR=365*5;END;

;RUN;




/*진단 후 2년내 암 치료 (수술, 항암, 방사선) 여부 데이터셋*/

/*진단 후 2년내 암 치료 (수술) 여부*/
PROC SQL; CREATE TABLE DB.T30_OP_2YR AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS OP_2YR_YN
FROM DB.TARGET_T30_LTC5YR
WHERE C_DATE<=T30_DATE<= INTNX('YEAR',C_DATE,2,'S') AND T30_DATE^=. AND OP^=" "  
ORDER BY INDI_DSCM_NO
; QUIT;
/*진단 후 2년내 암 치료 (항암) 여부*/
PROC SQL; CREATE TABLE DB.T30_CT_2YR AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS CT_2YR_YN
FROM DB.TARGET_T30_LTC5YR
WHERE C_DATE<=T30_DATE<= INTNX('YEAR',C_DATE,2,'S') AND T30_DATE^=. AND CTx^=" " 
ORDER BY INDI_DSCM_NO
; QUIT;
/*진단 후 2년내 암 치료 (방사선) 여부*/
PROC SQL; CREATE TABLE DB.T30_RT_2YR AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS RT_2YR_YN
FROM DB.TARGET_T30_LTC5YR
WHERE C_DATE<=T30_DATE<= INTNX('YEAR',C_DATE,2,'S') AND T30_DATE^=. AND RT^=" "
ORDER BY INDI_DSCM_NO
; QUIT;

DATA TRT_2YR_YN; MERGE DB.T30_OP_2YR DB.T30_CT_2YR DB.T30_RT_2YR; BY INDI_DSCM_NO ; RUN;

DATA TRT_2YR_GRP/*(DROP=OP_2YR_YN CT_2YR_YN RT_2YR_YN)*/; SET TRT_2YR_YN;
IF OP_2YR_YN=1 AND CT_2YR_YN=. AND RT_2YR_YN=. THEN TRT_GRP_2YR="01. Only OP";
ELSE IF OP_2YR_YN=. AND CT_2YR_YN=1 AND RT_2YR_YN=. THEN TRT_GRP_2YR="02. Only CT";
ELSE IF OP_2YR_YN=. AND CT_2YR_YN=. AND RT_2YR_YN=1 THEN TRT_GRP_2YR="03. Only RT";
ELSE IF OP_2YR_YN=1 AND CT_2YR_YN=1 AND RT_2YR_YN=. THEN TRT_GRP_2YR="04. OP+CT";
ELSE IF OP_2YR_YN=1 AND CT_2YR_YN=. AND RT_2YR_YN=1 THEN TRT_GRP_2YR="05. OP+RT";
ELSE IF OP_2YR_YN=. AND CT_2YR_YN=1 AND RT_2YR_YN=1 THEN TRT_GRP_2YR="06. CT+RT";
ELSE IF OP_2YR_YN=1 AND CT_2YR_YN=1 AND RT_2YR_YN=1 THEN TRT_GRP_2YR="06. OP+CT+RT";
RUN;



/*치료여부 붙이기*/
PROC SQL; CREATE TABLE LTC_FULLDAT2 AS
SELECT A.*, B.*
FROM LTC_FULLDAT1 AS A
LEFT JOIN TRT_2YR_GRP AS B
ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
;QUIT;

DATA DB.LTC_FULLDAT; SET LTC_FULLDAT2;
IF TRT_GRP_2YR='' THEN TRT_GRP_2YR='00. No Trt';
RUN;



/*2010년 이후 환자 대상 TABLES*/
/*환자 수 TABLES*/
libname TB "/userdata20/rroom029/data_out/data_out/TABLES";

PROC SQL; CREATE TABLE TB.TRT_SEXAGE_2010 AS
SELECT TRT_GRP_2YR, SEX_TYPE, AGE_GRP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0 AND C_YEAR>=2010
GROUP BY TRT_GRP_2YR, SEX_TYPE, AGE_GRP 
;QUIT;

PROC SQL; CREATE TABLE TB.TRT_CYEAR_2010 AS
SELECT TRT_GRP_2YR, C_YEAR, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0 AND C_YEAR>=2010
GROUP BY TRT_GRP_2YR, C_YEAR
;QUIT;

/*PROC SQL; CREATE TABLE TRT_CYEARGRP AS
SELECT TRT_GRP_2YR, C_YEAR_GRP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0  AND C_YEAR>=2010
GROUP BY TRT_GRP_2YR, C_YEAR_GRP
;QUIT;*/


PROC SQL; CREATE TABLE TB.LTC_SEXAGE_2010 AS
SELECT MAIN_USE_2YR, SEX_TYPE, E_AGE_GRP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0 AND E_AGE_GRP^='' AND C_YEAR>=2010
GROUP BY MAIN_USE_2YR, SEX_TYPE, E_AGE_GRP 
;QUIT;

PROC SQL; CREATE TABLE TB.LTC_CYEAR_2010 AS
SELECT MAIN_USE_2YR, C_YEAR, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0 AND E_AGE_GRP^='' AND C_YEAR>=2010
GROUP BY MAIN_USE_2YR, C_YEAR
;QUIT;

PROC SQL; CREATE TABLE TB.LTC_TRT_2010 AS
SELECT SEX_TYPE, E_AGE_GRP, TRT_GRP_2YR, MAIN_USE_2YR, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0 AND E_AGE_GRP^='' AND C_YEAR>=2010
GROUP BY SEX_TYPE, E_AGE_GRP, TRT_GRP_2YR, MAIN_USE_2YR
;QUIT;


/*진단이후 경과연별로 이용한 사람 수, 성별 연령별, 복수이용자 중복 카운트*/
%MACRO SERV_YN_YR;
%DO YR=1 %TO 10;
/*비누적  YR*/
PROC SQL; CREATE TABLE ADJ_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS ADJ_YN_&YR.
FROM DB.TARGET_ADJ
WHERE INTNX('YEAR',C_DATE,%EVAL(&YR.-1),'S')<=INPUT(MDCARE_STRT_DT,YYMMDD10.) <INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0
AND C_YEAR>=2010
;QUIT;
PROC SQL; CREATE TABLE INS_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS INS_YN_&YR.
FROM DB.TARGET_LTCP
WHERE INTNX('YEAR',C_DATE,%EVAL(&YR.-1),'S')<=INPUT(LTCP_FR_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0 AND LTCP_TYPE_CD = '1'
AND C_YEAR>=2010
;QUIT;
PROC SQL; CREATE TABLE HOME_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS HOME_YN_&YR.
FROM DB.TARGET_LTCP
WHERE INTNX('YEAR',C_DATE,%EVAL(&YR.-1),'S')<=INPUT(LTCP_FR_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0 AND LTCP_TYPE_CD = '2'
AND C_YEAR>=2010
;QUIT;

/*누적 YR*/
PROC SQL; CREATE TABLE CUM_ADJ_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS ADJ_YN_&YR.
FROM DB.TARGET_ADJ
WHERE C_DATE<=INPUT(MDCARE_STRT_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0
AND C_YEAR>=2010
;QUIT;
PROC SQL; CREATE TABLE CUM_INS_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS INS_YN_&YR.
FROM DB.TARGET_LTCP
WHERE C_DATE<=INPUT(LTCP_FR_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0 AND LTCP_TYPE_CD = '1'
AND C_YEAR>=2010
;QUIT;
PROC SQL; CREATE TABLE CUM_HOME_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, 1 AS HOME_YN_&YR.
FROM DB.TARGET_LTCP
WHERE C_DATE<=INPUT(LTCP_FR_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0 AND LTCP_TYPE_CD = '2'
AND C_YEAR>=2010
;QUIT;
%END;
%MEND; %SERV_YN_YR;

/*비누적이용자 수 테이블*/
DATA SERV_YN_1TO10YR; MERGE ADJ_YN_1-ADJ_YN_10 INS_YN_1-INS_YN_10 HOME_YN_1-HOME_YN_10; BY INDI_DSCM_NO;RUN;

DATA TARGET_E_AGEGRP; SET DB.TARGET_ID;
IF 65<= C_AGE<75 THEN E_AGE_GRP='01. 65-74'; /*ELDERLY AGE GRP*/
ELSE IF 75 <= C_AGE <85 THEN E_AGE_GRP='02. 75-84';
ELSE IF 78 <= C_AGE THEN E_AGE_GRP='03. 85+';
WHERE C_AGE>=65;
RUN;

PROC SQL; CREATE TABLE SURV_YN_DAT AS
SELECT A.SEX_TYPE, A.E_AGE_GRP, A.C_YEAR, B.* /*혹시몰라서 C_YEAR도 넣음*/
FROM TARGET_E_AGEGRP AS A
INNER JOIN SERV_YN_1TO10YR AS B
ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
;QUIT;

PROC SQL; CREATE TABLE TB.SERV_USE_CNT AS
SELECT SEX_TYPE, E_AGE_GRP, 
SUM(ADJ_YN_1) AS ADJ1_CNT, SUM(ADJ_YN_2) AS ADJ2_CNT, SUM(ADJ_YN_3) AS ADJ3_CNT, SUM(ADJ_YN_4) AS ADJ4_CNT, SUM(ADJ_YN_5) AS ADJ5_CNT,  
SUM(ADJ_YN_6) AS ADJ6_CNT, SUM(ADJ_YN_7) AS ADJ7_CNT, SUM(ADJ_YN_8) AS ADJ8_CNT, SUM(ADJ_YN_9) AS ADJ9_CNT, SUM(ADJ_YN_10) AS ADJ10_CNT,
SUM(INS_YN_1) AS INS1_CNT, SUM(INS_YN_2) AS INS2_CNT, SUM(INS_YN_3) AS INS3_CNT, SUM(INS_YN_4) AS INS4_CNT, SUM(INS_YN_5) AS INS5_CNT, 
SUM(INS_YN_6) AS INS6_CNT, SUM(INS_YN_7) AS INS7_CNT, SUM(INS_YN_8) AS INS8_CNT, SUM(INS_YN_9) AS INS9_CNT, SUM(INS_YN_10) AS INS10_CNT,
SUM(HOME_YN_1) AS HOME1_CNT, SUM(HOME_YN_2) AS HOME2_CNT, SUM(HOME_YN_3) AS HOME3_CNT, SUM(HOME_YN_4) AS HOME4_CNT, SUM(HOME_YN_5) AS HOME5_CNT, 
SUM(HOME_YN_6) AS HOME6_CNT, SUM(HOME_YN_7) AS HOME7_CNT, SUM(HOME_YN_8) AS HOME8_CNT, SUM(HOME_YN_9) AS HOME9_CNT, SUM(HOME_YN_10) AS HOME10_CNT
FROM SURV_YN_DAT
GROUP BY SEX_TYPE, E_AGE_GRP
;QUIT;

/*누적이용자 수 테이블*/
DATA CUM_SERV_YN_1TO10YR; MERGE CUM_ADJ_YN_1-CUM_ADJ_YN_10 CUM_INS_YN_1-CUM_INS_YN_10 CUM_HOME_YN_1-CUM_HOME_YN_10; BY INDI_DSCM_NO;RUN;

PROC SQL; CREATE TABLE CUM_SURV_YN_DAT AS
SELECT A.SEX_TYPE, A.E_AGE_GRP, A.C_YEAR, B.* /*혹시몰라서 C_YEAR도 넣음*/
FROM TARGET_E_AGEGRP AS A
INNER JOIN CUM_SERV_YN_1TO10YR AS B
ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
;QUIT;

PROC SQL; CREATE TABLE TB.CUM_SERV_USE_CNT AS
SELECT SEX_TYPE, E_AGE_GRP, 
SUM(ADJ_YN_1) AS ADJ1_CNT, SUM(ADJ_YN_2) AS ADJ2_CNT, SUM(ADJ_YN_3) AS ADJ3_CNT, SUM(ADJ_YN_4) AS ADJ4_CNT, SUM(ADJ_YN_5) AS ADJ5_CNT,  
SUM(ADJ_YN_6) AS ADJ6_CNT, SUM(ADJ_YN_7) AS ADJ7_CNT, SUM(ADJ_YN_8) AS ADJ8_CNT, SUM(ADJ_YN_9) AS ADJ9_CNT, SUM(ADJ_YN_10) AS ADJ10_CNT,
SUM(INS_YN_1) AS INS1_CNT, SUM(INS_YN_2) AS INS2_CNT, SUM(INS_YN_3) AS INS3_CNT, SUM(INS_YN_4) AS INS4_CNT, SUM(INS_YN_5) AS INS5_CNT, 
SUM(INS_YN_6) AS INS6_CNT, SUM(INS_YN_7) AS INS7_CNT, SUM(INS_YN_8) AS INS8_CNT, SUM(INS_YN_9) AS INS9_CNT, SUM(INS_YN_10) AS INS10_CNT,
SUM(HOME_YN_1) AS HOME1_CNT, SUM(HOME_YN_2) AS HOME2_CNT, SUM(HOME_YN_3) AS HOME3_CNT, SUM(HOME_YN_4) AS HOME4_CNT, SUM(HOME_YN_5) AS HOME5_CNT, 
SUM(HOME_YN_6) AS HOME6_CNT, SUM(HOME_YN_7) AS HOME7_CNT, SUM(HOME_YN_8) AS HOME8_CNT, SUM(HOME_YN_9) AS HOME9_CNT, SUM(HOME_YN_10) AS HOME10_CNT
FROM CUM_SURV_YN_DAT
GROUP BY SEX_TYPE, E_AGE_GRP
;QUIT;







/*휴지통*/
/*이용일 수 기준*/
%MACRO DD_CNT(WI_YR);
/*ADJ  암진단이후 &WI_YR.년 내 요양일수 합*/
PROC SQL; CREATE TABLE COUNT_DD_ADJ_&WI_YR.YR AS
SELECT INDI_DSCM_NO, SUM(MDCARE_DD_CNT) AS DD_&WI_YR.YR_ADJ
FROM DB.TARGET_ADJ
WHERE C_DATE < INPUT(MDCARE_STRT_DT,YYMMDD10.) < INTNX('YEAR',C_DATE,&WI_YR.,'S')
GROUP BY INDI_DSCM_NO
ORDER BY INDI_DSCM_NO
;QUIT;
/*시설 암 진단이후 &WI_YR.년 내 심사조정총급여일수 합*/
PROC SQL; CREATE TABLE COUNT_DD_INS_&WI_YR.YR AS
SELECT INDI_DSCM_NO, SUM(EADJ_TOTAL_PAY_DCNT) AS DD_&WI_YR.YR_INS
FROM DB.TARGET_LTCP
WHERE C_DATE < INPUT(LTCP_FR_DT,YYMMDD10.) < INTNX('YEAR',C_DATE,&WI_YR.,'S')
AND LTCP_TYPE_CD = '1'
GROUP BY INDI_DSCM_NO
ORDER BY INDI_DSCM_NO
;QUIT;
/*재가 암 진단이후 &WI_YR.년 내 심사조정총급여일수 합*/
PROC SQL; CREATE TABLE COUNT_DD_HOME_&WI_YR.YR AS
SELECT INDI_DSCM_NO, SUM(EADJ_TOTAL_PAY_DCNT) AS DD_&WI_YR.YR_HOME
FROM DB.TARGET_LTCP
WHERE C_DATE < INPUT(LTCP_FR_DT,YYMMDD10.) < INTNX('YEAR',C_DATE,&WI_YR.,'S')
AND LTCP_TYPE_CD = '2'
GROUP BY INDI_DSCM_NO
ORDER BY INDI_DSCM_NO
;QUIT;

DATA CNT_DD_&WI_YR.YR; MERGE COUNT_DD_ADJ_&WI_YR.YR COUNT_DD_INS_&WI_YR.YR COUNT_DD_HOME_&WI_YR.YR; BY INDI_DSCM_NO; RUN;

/*암 진단이후 &WI_YR.년 내 최다 이용일 수, 최다일 이용 기관*/
DATA MAX_DD_&WI_YR.YR; SET CNT_DD_&WI_YR.YR;
N_&WI_YR.YR = N(OF DD_&WI_YR.YR_ADJ, DD_&WI_YR.YR_INS, DD_&WI_YR.YR_HOME);
MAX_DD_&WI_YR.YR = MAX(DD_&WI_YR.YR_ADJ, DD_&WI_YR.YR_INS, DD_&WI_YR.YR_HOME);
IF MAX_DD_&WI_YR.YR = DD_&WI_YR.YR_ADJ THEN MAIN_USE_&WI_YR. = '03. 요양병원';
ELSE IF MAX_DD_&WI_YR.YR = DD_&WI_YR.YR_INS THEN MAIN_USE_&WI_YR. = '01. 시설';
ELSE IF MAX_DD_&WI_YR.YR = DD_&WI_YR.YR_HOME THEN MAIN_USE_&WI_YR. = '02. 재가'
; RUN;

%MEND;

%DD_CNT(2);/*34874*/
%DD_CNT(5);/*44484*/
%DD_CNT(10);/*49242*/

/*DATA MAX_2510(KEEP=INDI_DSCM_NO MAIN_USE_2 MAIN_USE_5 MAIN_USE_10); 
MERGE MAX_DD_2YR MAX_DD_5YR MAX_DD_10YR; BY INDI_DSCM_NO; RUN;

DATA MAX_2510_VAR; SET MAX_2510;
IF MAIN_USE_2 ^='' AND MAIN_USE_5 ^='' AND MAIN_USE_2 = MAIN_USE_5 = MAIN_USE_10 THEN VAR = 0;
ELSE IF MAIN_USE_2='' AND MAIN_USE_5 ^='' AND MAIN_USE_5 = MAIN_USE_10 THEN VAR = 0;
ELSE IF MAIN_USE_2='' AND MAIN_USE_5 ='' THEN VAR = 0;
ELSE VAR=1;
RUN;

PROC SQL; CREATE TABLE VAR1 AS SELECT * FROM MAX_2510_VAR WHERE VAR=1; QUIT; 
*/
/*주이용서비스가 변동되는 사람 578명, 전체10년내이용자의 11%*/


/*복수의 요양기관을 이용하면 요양일수가 각각 카운트 됨 */
DATA TEST; SET USE2_2YR; WHERE MAX_DD_2YR>700; RUN;

PROC SQL; CREATE TABLE TEST AS SELECT * FROM RAW.RVSN_HFVT_TBNYPAY
WHERE INDI_DSCM_NO=29715982 ORDER BY LTC_OR_SYM, LTCP_FR_DT; QUIT;

%LET WI_YR=2;
DATA TEST; SET  COUNT_DD_HOME_2YR; WHERE INDI_DSCM_NO=22824188; RUN;

PROC SQL; CREATE TABLE COUNT_DD_HOME_&WI_YR.YR AS
SELECT *
FROM DB.TARGET_LTCP
WHERE C_DATE < INPUT(LTCP_FR_DT,YYMMDD10.) < INTNX('YEAR',C_DATE,&WI_YR.,'S') AND INDI_DSCM_NO=22824188
AND LTCP_TYPE_CD = '2'
ORDER BY INDI_DSCM_NO
;QUIT;

/*2008년 이후*/
/*환자 수 TABLES*/
libname TB "/userdata20/rroom029/data_out/data_out/TABLES";

PROC SQL; CREATE TABLE TB.TRT_SEXAGE AS
SELECT TRT_GRP_2YR, SEX_TYPE, AGE_GRP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0
GROUP BY TRT_GRP_2YR, SEX_TYPE, AGE_GRP 
;QUIT;

PROC SQL; CREATE TABLE TB.TRT_CYEAR AS
SELECT TRT_GRP_2YR, C_YEAR, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0
GROUP BY TRT_GRP_2YR, C_YEAR
;QUIT;

/*PROC SQL; CREATE TABLE TRT_CYEARGRP AS
SELECT TRT_GRP_2YR, C_YEAR_GRP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0
GROUP BY TRT_GRP_2YR, C_YEAR_GRP
;QUIT;*/


PROC SQL; CREATE TABLE TB.LTC_SEXAGE AS
SELECT MAIN_USE_2YR, SEX_TYPE, E_AGE_GRP, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0 AND E_AGE_GRP^=''
GROUP BY MAIN_USE_2YR, SEX_TYPE, E_AGE_GRP 
;QUIT;

PROC SQL; CREATE TABLE TB.LTC_CYEAR AS
SELECT MAIN_USE_2YR, C_YEAR, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0 AND E_AGE_GRP^=''
GROUP BY MAIN_USE_2YR, C_YEAR
;QUIT;

PROC SQL; CREATE TABLE TB.LTC_TRT AS
SELECT SEX_TYPE, E_AGE_GRP, TRT_GRP_2YR, MAIN_USE_2YR, COUNT(DISTINCT INDI_DSCM_NO) AS CNT
FROM DB.LTC_FULLDAT
WHERE PRE_C=0 AND E_AGE_GRP^=''
GROUP BY SEX_TYPE, E_AGE_GRP, TRT_GRP_2YR, MAIN_USE_2YR
;QUIT;


/*0523추가*/

/*진단이후 경과연별로 장기요양서비스를 이용한 사람 수, 성별 연령별, 복수이용자 중복 카운트*/
%MACRO SERV_YN_YR;
%DO YR=1 %TO 10;
/*비누적 YR*/
PROC SQL; CREATE TABLE ADJ_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, C_YEAR, 1 AS ADJ_YN_&YR.
FROM DB.TARGET_ADJ
WHERE INTNX('YEAR',C_DATE,%EVAL(&YR.-1),'S')<=INPUT(MDCARE_STRT_DT,YYMMDD10.) <INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0
;QUIT;
PROC SQL; CREATE TABLE INS_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, C_YEAR, 1 AS INS_YN_&YR.
FROM DB.TARGET_LTCP
WHERE INTNX('YEAR',C_DATE,%EVAL(&YR.-1),'S')<=INPUT(LTCP_FR_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0 AND LTCP_TYPE_CD = '1'
;QUIT;
PROC SQL; CREATE TABLE HOME_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, C_YEAR, 1 AS HOME_YN_&YR.
FROM DB.TARGET_LTCP
WHERE INTNX('YEAR',C_DATE,%EVAL(&YR.-1),'S')<=INPUT(LTCP_FR_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0 AND LTCP_TYPE_CD = '2'
;QUIT;

/*누적 YR*/
PROC SQL; CREATE TABLE CUM_ADJ_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, C_YEAR, 1 AS ADJ_YN_&YR.
FROM DB.TARGET_ADJ
WHERE C_DATE<=INPUT(MDCARE_STRT_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0
;QUIT;
PROC SQL; CREATE TABLE CUM_INS_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, C_YEAR, 1 AS INS_YN_&YR.
FROM DB.TARGET_LTCP
WHERE C_DATE<=INPUT(LTCP_FR_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0 AND LTCP_TYPE_CD = '1'
;QUIT;
PROC SQL; CREATE TABLE CUM_HOME_YN_&YR. AS
SELECT DISTINCT INDI_DSCM_NO, C_YEAR, 1 AS HOME_YN_&YR.
FROM DB.TARGET_LTCP
WHERE C_DATE<=INPUT(LTCP_FR_DT,YYMMDD10.)<INTNX('YEAR',C_DATE,&YR.,'S') AND PRE_C=0 AND LTCP_TYPE_CD = '2'
;QUIT;
%END;
%MEND; %SERV_YN_YR;

/*비누적*/
DATA SERV_YN_1TO10YR; MERGE ADJ_YN_1-ADJ_YN_10 INS_YN_1-INS_YN_10 HOME_YN_1-HOME_YN_10; BY INDI_DSCM_NO;RUN;

DATA TARGET_E_AGEGRP; SET DB.TARGET_ID;
IF 65<= C_AGE<75 THEN E_AGE_GRP='01. 65-74'; /*ELDERLY AGE GRP*/
ELSE IF 75 <= C_AGE <85 THEN E_AGE_GRP='02. 75-84';
ELSE IF 78 <= C_AGE THEN E_AGE_GRP='03. 85+';
WHERE C_AGE>=65;
RUN;

PROC SQL; CREATE TABLE SURV_YN_DAT AS
SELECT A.SEX_TYPE, A.E_AGE_GRP, A.C_YEAR, B.* /*혹시몰라서 C_YEAR도 넣음*/
FROM TARGET_E_AGEGRP AS A
INNER JOIN SERV_YN_1TO10YR AS B
ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
;QUIT;

PROC SQL; CREATE TABLE SERV_USE_CNT AS
SELECT SEX_TYPE, E_AGE_GRP, 
SUM(ADJ_YN_1) AS ADJ1_CNT, SUM(ADJ_YN_2) AS ADJ2_CNT, SUM(ADJ_YN_3) AS ADJ3_CNT, SUM(ADJ_YN_4) AS ADJ4_CNT, SUM(ADJ_YN_5) AS ADJ5_CNT,  
SUM(ADJ_YN_6) AS ADJ6_CNT, SUM(ADJ_YN_7) AS ADJ7_CNT, SUM(ADJ_YN_8) AS ADJ8_CNT, SUM(ADJ_YN_9) AS ADJ9_CNT, SUM(ADJ_YN_10) AS ADJ10_CNT,
SUM(INS_YN_1) AS INS1_CNT, SUM(INS_YN_2) AS INS2_CNT, SUM(INS_YN_3) AS INS3_CNT, SUM(INS_YN_4) AS INS4_CNT, SUM(INS_YN_5) AS INS5_CNT, 
SUM(INS_YN_6) AS INS6_CNT, SUM(INS_YN_7) AS INS7_CNT, SUM(INS_YN_8) AS INS8_CNT, SUM(INS_YN_9) AS INS9_CNT, SUM(INS_YN_10) AS INS10_CNT,
SUM(HOME_YN_1) AS HOME1_CNT, SUM(HOME_YN_2) AS HOME2_CNT, SUM(HOME_YN_3) AS HOME3_CNT, SUM(HOME_YN_4) AS HOME4_CNT, SUM(HOME_YN_5) AS HOME5_CNT, 
SUM(HOME_YN_6) AS HOME6_CNT, SUM(HOME_YN_7) AS HOME7_CNT, SUM(HOME_YN_8) AS HOME8_CNT, SUM(HOME_YN_9) AS HOME9_CNT, SUM(HOME_YN_10) AS HOME10_CNT
FROM SURV_YN_DAT
GROUP BY SEX_TYPE, E_AGE_GRP
;QUIT;

PROC SQL; CREATE TABLE SERV_USE_CNT_CYEAR AS
SELECT SEX_TYPE, E_AGE_GRP, C_YEAR,
SUM(ADJ_YN_1) AS ADJ1_CNT, SUM(ADJ_YN_2) AS ADJ2_CNT, SUM(ADJ_YN_3) AS ADJ3_CNT, SUM(ADJ_YN_4) AS ADJ4_CNT, SUM(ADJ_YN_5) AS ADJ5_CNT,  
SUM(ADJ_YN_6) AS ADJ6_CNT, SUM(ADJ_YN_7) AS ADJ7_CNT, SUM(ADJ_YN_8) AS ADJ8_CNT, SUM(ADJ_YN_9) AS ADJ9_CNT, SUM(ADJ_YN_10) AS ADJ10_CNT,
SUM(INS_YN_1) AS INS1_CNT, SUM(INS_YN_2) AS INS2_CNT, SUM(INS_YN_3) AS INS3_CNT, SUM(INS_YN_4) AS INS4_CNT, SUM(INS_YN_5) AS INS5_CNT, 
SUM(INS_YN_6) AS INS6_CNT, SUM(INS_YN_7) AS INS7_CNT, SUM(INS_YN_8) AS INS8_CNT, SUM(INS_YN_9) AS INS9_CNT, SUM(INS_YN_10) AS INS10_CNT,
SUM(HOME_YN_1) AS HOME1_CNT, SUM(HOME_YN_2) AS HOME2_CNT, SUM(HOME_YN_3) AS HOME3_CNT, SUM(HOME_YN_4) AS HOME4_CNT, SUM(HOME_YN_5) AS HOME5_CNT, 
SUM(HOME_YN_6) AS HOME6_CNT, SUM(HOME_YN_7) AS HOME7_CNT, SUM(HOME_YN_8) AS HOME8_CNT, SUM(HOME_YN_9) AS HOME9_CNT, SUM(HOME_YN_10) AS HOME10_CNT
FROM SURV_YN_DAT
GROUP BY SEX_TYPE, E_AGE_GRP, C_YEAR
;QUIT;


/*누적*/
DATA CUM_SERV_YN_1TO10YR; MERGE CUM_ADJ_YN_1-CUM_ADJ_YN_10 CUM_INS_YN_1-CUM_INS_YN_10 CUM_HOME_YN_1-CUM_HOME_YN_10; BY INDI_DSCM_NO;RUN;

PROC SQL; CREATE TABLE CUM_SURV_YN_DAT AS
SELECT A.SEX_TYPE, A.E_AGE_GRP, A.C_YEAR, B.* /*혹시몰라서 C_YEAR도 넣음*/
FROM TARGET_E_AGEGRP AS A
INNER JOIN CUM_SERV_YN_1TO10YR AS B
ON A.INDI_DSCM_NO=B.INDI_DSCM_NO
;QUIT;

PROC SQL; CREATE TABLE CUM_SERV_USE_CNT AS
SELECT SEX_TYPE, E_AGE_GRP, 
SUM(ADJ_YN_1) AS ADJ1_CNT, SUM(ADJ_YN_2) AS ADJ2_CNT, SUM(ADJ_YN_3) AS ADJ3_CNT, SUM(ADJ_YN_4) AS ADJ4_CNT, SUM(ADJ_YN_5) AS ADJ5_CNT,  
SUM(ADJ_YN_6) AS ADJ6_CNT, SUM(ADJ_YN_7) AS ADJ7_CNT, SUM(ADJ_YN_8) AS ADJ8_CNT, SUM(ADJ_YN_9) AS ADJ9_CNT, SUM(ADJ_YN_10) AS ADJ10_CNT,
SUM(INS_YN_1) AS INS1_CNT, SUM(INS_YN_2) AS INS2_CNT, SUM(INS_YN_3) AS INS3_CNT, SUM(INS_YN_4) AS INS4_CNT, SUM(INS_YN_5) AS INS5_CNT, 
SUM(INS_YN_6) AS INS6_CNT, SUM(INS_YN_7) AS INS7_CNT, SUM(INS_YN_8) AS INS8_CNT, SUM(INS_YN_9) AS INS9_CNT, SUM(INS_YN_10) AS INS10_CNT,
SUM(HOME_YN_1) AS HOME1_CNT, SUM(HOME_YN_2) AS HOME2_CNT, SUM(HOME_YN_3) AS HOME3_CNT, SUM(HOME_YN_4) AS HOME4_CNT, SUM(HOME_YN_5) AS HOME5_CNT, 
SUM(HOME_YN_6) AS HOME6_CNT, SUM(HOME_YN_7) AS HOME7_CNT, SUM(HOME_YN_8) AS HOME8_CNT, SUM(HOME_YN_9) AS HOME9_CNT, SUM(HOME_YN_10) AS HOME10_CNT
FROM CUM_SURV_YN_DAT
GROUP BY SEX_TYPE, E_AGE_GRP
;QUIT;

PROC SQL; CREATE TABLE CUM_SERV_USE_CNT_CYEAR AS
SELECT SEX_TYPE, E_AGE_GRP, C_YEAR,
SUM(ADJ_YN_1) AS ADJ1_CNT, SUM(ADJ_YN_2) AS ADJ2_CNT, SUM(ADJ_YN_3) AS ADJ3_CNT, SUM(ADJ_YN_4) AS ADJ4_CNT, SUM(ADJ_YN_5) AS ADJ5_CNT,  
SUM(ADJ_YN_6) AS ADJ6_CNT, SUM(ADJ_YN_7) AS ADJ7_CNT, SUM(ADJ_YN_8) AS ADJ8_CNT, SUM(ADJ_YN_9) AS ADJ9_CNT, SUM(ADJ_YN_10) AS ADJ10_CNT,
SUM(INS_YN_1) AS INS1_CNT, SUM(INS_YN_2) AS INS2_CNT, SUM(INS_YN_3) AS INS3_CNT, SUM(INS_YN_4) AS INS4_CNT, SUM(INS_YN_5) AS INS5_CNT, 
SUM(INS_YN_6) AS INS6_CNT, SUM(INS_YN_7) AS INS7_CNT, SUM(INS_YN_8) AS INS8_CNT, SUM(INS_YN_9) AS INS9_CNT, SUM(INS_YN_10) AS INS10_CNT,
SUM(HOME_YN_1) AS HOME1_CNT, SUM(HOME_YN_2) AS HOME2_CNT, SUM(HOME_YN_3) AS HOME3_CNT, SUM(HOME_YN_4) AS HOME4_CNT, SUM(HOME_YN_5) AS HOME5_CNT, 
SUM(HOME_YN_6) AS HOME6_CNT, SUM(HOME_YN_7) AS HOME7_CNT, SUM(HOME_YN_8) AS HOME8_CNT, SUM(HOME_YN_9) AS HOME9_CNT, SUM(HOME_YN_10) AS HOME10_CNT
FROM CUM_SURV_YN_DAT
GROUP BY SEX_TYPE, E_AGE_GRP, C_YEAR
;QUIT;
